### ISSUE TITLE
commands

### ISSUE THREAD

**Issue by coolkidsrule101** [EssentialPMMP/ShopUI#3]
where are the commands to perform this operation of this plugin

**Comment by armagadon159753** [comment]
I will add the /shop dont worry

**Comment by coolkidsrule101** [comment]
ok and when i clicked on the shop buttons nothing happens. pls also fix when clicking your hand to not bring up the ui please that kinda anyonig when ppl fight

**Comment by armagadon159753** [comment]
test now with /shopui

**Comment by coolkidsrule101** [comment]
ok

**Comment by coolkidsrule101** [comment]
hey nope there no command and i also check the code and i dont see any command line
