### ISSUE TITLE
no cammand showing up

### ISSUE THREAD

**Issue by coolkidsrule101** [EssentialPMMP/ShopUI#4]

**Comment by armagadon159753** [comment]
Try now

**Comment by coolkidsrule101** [comment]
yes it now showing commands

**Comment by coolkidsrule101** [comment]
now fix buttons nothing showing up to purchesed for players

**Comment by armagadon159753** [comment]
Wich
Send me screen

**Comment by coolkidsrule101** [comment]
ok

**Comment by coolkidsrule101** [comment]
sorry i was just eating 

[github.mp4.zip](https://github.com/EssentialPMMP/ShopUI/files/1485138/github.mp4.zip)

**Comment by armagadon159753** [comment]
Any arror in  console

**Comment by coolkidsrule101** [comment]
no

**Comment by armagadon159753** [comment]
Make your sur you have last comit

**Comment by coolkidsrule101** [comment]
huh

**Comment by armagadon159753** [comment]
That work fine for my

Le 19 nov. 2017 01:19, "coolkidsrule101" <notifications@github.com> a
écrit :

**Comment by coolkidsrule101** [comment]
ok i wil reset my server to see if it works again

**Comment by coolkidsrule101** [comment]
also the blocks button doesnt show any thing but i got everything else to work it was a plugin inferance with your plugin
